// lib/vue-calendar/src/index.vue
<template>
  <div class="zx-vue-calendar">
    <slot name="header"></slot>
    <div ref="el" class="zx-calendar-wrapper"></div>
    <slot name="footer"></slot>
  </div>
</template>

<script>
  import ZxCalendar from '../../../src/index'
  import { MODE_SINGLE, TYPE_DATE, DEF_OPTIONS } from '../../constants'

  export default {
    name: 'ZxVueCalendar',
    props: {
      value: {
        type: [String, Number, Array],
        default: ''
      },
      type: {
        type: String,
        default: TYPE_DATE
      },
      mode: {
        type: String,
        default: MODE_SINGLE
      },
      format: {
        type: String,
        default: ''
      },
      lang: {
        type: String,
        default: 'en'
      },
      isFullWeek: Boolean,
      titleFormatter: {
        type: String,
        default: ''
      },
      itemSuffix: {
        type: String,
        default: ''
      },
      dateRange: {
        type: Array,
        default: () => []
      },
      showHoliday: Boolean,
      itemFormatter: {
        type: Function,
        default: undefined
      },
      langPackage: {
        type: Object,
        default: undefined
      },
      footerButtons: {
        type: Array,
        default: undefined
      },
      footerButtonAlign: {
        type: String,
        default: 'flex-end'
      },
      hideFooter: Boolean,
      option: {
        type: Object,
        default:() => {}
      }
    },
    data() {
      return {
        calendar: null,
        date: this.value
      }
    },
    computed: {
      options() {
        const ret = {
          ...this.option
        }
        let val
        Object.keys(DEF_OPTIONS).forEach(key => {
          val = this[key]
          if (val) {
            if (!Array.isArray(DEF_OPTIONS[key]) || DEF_OPTIONS[key].includes(val)) {
              ret[key] = val
            }
          }
        })
        return ret
      },
      fmt() {
        return typeof this.format === 'string' ? this.format : null
      }
    },
    mounted() {
      const calendar = new ZxCalendar({
        ...this.options,
        el: this.$refs.el,
        defaultDate: this.date
      })

      calendar.on('change', list => {
        this.date = this._fmtValue(list)
        this.$emit('change', this.date, list)
      })

      calendar.on('error', err => {
        this.$emit('error', err)
      })

      calendar.on('cancel', () => {
        this.$emit('cancel')
      })

      this.calendar = calendar
      this.$emit('instance', calendar)
    },
    methods: {
      setDate(str) {
        this.calendar.setDate(str)
      },
      toDate(str) {
        return this.calendar.toDate(str)
      },
      formatDate(date, formatter, langPackage) {
        return this.calendar.formatDate(date, formatter, langPackage)
      },
      setCurrentDate(str) {
        this.calendar.setCurrentDate(str)
      },
      setDateRange(startDate, endDate) {
        this.calendar.setDateRange(startDate, endDate)
      },
      prev(isYear) {
        this.calendar.prev(isYear)
      },
      next(isYear) {
        this.calendar.next(isYear)
      },
      getDate() {
        return this.calendar.getDate()
      },
      _fmtValue(list) {
        const fmt = this.fmt
        const arr = list.map(item => {
          return fmt ? this.calendar.formatDate(item.fullText, fmt) : item.fullText
        })
        return this.mode === MODE_SINGLE ? arr[0] : arr
      }
    },
    watch: {
      value(val) {
        if (this.date !== val) {
          this.date = val
          this.setDate(val)
        }
      },
      date(val) {
        this.$emit('input', val)
      }
    }
  }
</script>

// lib/react-calendar/src/index.jsx
/**
 * Created by Capricorncd.
 * https://github.com/capricorncd
 * Date: 2020-09-11 21:48
 */
import React, { Component } from 'react'
import PropTypes from 'prop-types'
import ZxCalendar from '../../../src/index'
import { DEF_OPTIONS, MODE_SINGLE, TYPE_DATE } from '../../constants'
import { isFunction } from './helper'

class ZxReactCalendar extends Component {
  constructor(props) {
    super(props)
    this.el = React.createRef()
    this.calendar = null
    this.options = this._initOptions()
    this.state = {
      date: props.value
    }
  }

  setDate(str) {
    this.calendar.setDate(str)
  }

  toDate(str) {
    return this.calendar.toDate(str)
  }

  formatDate(date, formatter, langPackage) {
    return this.calendar.formatDate(date, formatter, langPackage)
  }

  setCurrentDate(str) {
    this.calendar.setCurrentDate(str)
  }

  setDateRange(startDate, endDate) {
    this.calendar.setDateRange(startDate, endDate)
  }

  prev(isYear) {
    this.calendar.prev(isYear)
  }

  next(isYear) {
    this.calendar.next(isYear)
  }

  getDate() {
    return this.calendar.getDate()
  }

  _fmtValue(list) {
    const fmt = this.fmt()
    const arr = list.map(item => {
      return fmt
        ? this.calendar.formatDate(item.fullText, fmt)
        : item.fullText
    })
    return this.props.mode === MODE_SINGLE ? arr[0] : arr
  }

  _initOptions() {
    const ret = {
      ...this.props.option
    }
    let val
    Object.keys(DEF_OPTIONS).forEach(key => {
      val = this.props[key]
      if (val) {
        if (!Array.isArray(DEF_OPTIONS[key]) || DEF_OPTIONS[key].includes(val)) {
          ret[key] = val
        }
      }
    })
    if (this.props.value) {
      ret.defaultDate = this.props.value
    }
    return ret
  }

  fmt() {
    const { format } = this.props
    return format && typeof format === 'string' ? format : null
  }

  componentDidMount() {
    const { instance, change, cancel, error } = this.props
    const calendar = new ZxCalendar({
      ...this.options,
      el: this.el.current
    })

    calendar.on('change', list => {
      const date = this._fmtValue(list)
      this.setState({
        date: date
      })
      if (isFunction(change)) {
        change(date, list)
      }
    })

    calendar.on('error', err => {
      if (isFunction(error)) {
        error(err)
      }
    })

    calendar.on('cancel', () => {
      if (isFunction(cancel)) {
        cancel()
      }
    })

    this.calendar = calendar

    if (isFunction(instance)) {
      instance(calendar)
    }
  }

  render() {
    return <div className="zx-react-calendar">
      {this.props.header}
      <div ref={this.el} className="zx-calendar-wrapper"></div>
      {this.props.footer}
    </div>
  }
}

ZxReactCalendar.propTypes = {
  type: PropTypes.string,
  mode: PropTypes.string,
  lang: PropTypes.string,
  isFullWeek: PropTypes.bool,
  titleFormatter: PropTypes.string,
  itemSuffix: PropTypes.string,
  dateRange: PropTypes.array,
  showHoliday: PropTypes.bool,
  itemFormatter: PropTypes.func,
  langPackage: PropTypes.object,
  footerButtons: PropTypes.array,
  footerButtonAlign: PropTypes.string,
  hideFooter: PropTypes.bool,
  value: PropTypes.oneOfType([
    PropTypes.string,
    PropTypes.number,
    PropTypes.array
  ]),
  format: PropTypes.string,
  change: PropTypes.func,
  cancel: PropTypes.func,
  error: PropTypes.func,
  instance: PropTypes.func,
  option: PropTypes.object,
  header: PropTypes.node,
  footer: PropTypes.node
}

ZxReactCalendar.defaultProps = {
  type: TYPE_DATE,
  mode: MODE_SINGLE,
  option: {}
}

export default ZxReactCalendar
